.travis.yml, SPTDataLoader.xcodeproj/xcshareddata/xcschemes/SPTDataLoader.xcscheme
Adds a simple travis CI component for the main component
=> Add travis CI

CONTRIBUTING.md
=> Add code of conduct to contributing document

.travis.yml
=> Only run push build for master and release-* branches

README.md
- License link was pointing to the wrong repo and file.
- Markup for the banner was a little bit flawed.
@8W9aG
=> Fix minor issues with readme

SPTDataLoaderTests/NSURLSessionDataTaskMock.h, SPTDataLoaderTests/NSURLSessionDataTaskMock.m, SPTDataLoaderTests/NSURLSessionMock.h, SPTDataLoaderTests/SPTDataLoaderServiceTest.m
=> Improve test coverage

.travis.yml, ci/after_success.sh, ci/before_install.sh, ci/script.sh
=> Organize ci

.travis.yml
=> Enable bundler caching

Gemfile, Gemfile.lock, ci/script.sh
=> Lint podspec

.gitignore, .travis.yml, SPTDataLoader.podspec, SPTDataLoader.xcodeproj/project.pbxproj, ci/script.sh
Experimental. Let's see if this works.
@jgavris @8W9aG @rastersize
=> Support OSX

README.md
=> Update README to reflect OS X support

SPTDataLoader.xcodeproj/project.pbxproj
Running tests from the Xcode IDE was broken (though xcodebuild still worked).
@8W9aG @rastersize @jgavris
=> Fix platform/arch config

.travis.yml, ci/before_install.sh
=> Use system libraries when building nokogiri

README.md
@8W9aG @jgavris @dflems @econchick
=> Add Spotify FOSS slack badge to readme

Gemfile, Gemfile.lock
=> Bump slather to venmo master

.travis.yml
* Made a mistake when putting in the root of deploy
=> Move tags: true to the on: section in travis

SPTDataLoader/SPTDataLoaderRequest.m, demo/SPTDataLoaderAuthoriserOAuth.m
I added constants according to the Spotify style guide
=> Style corrections

CHANGELOG.md
CocoaPods [likes project with a change log](https://guides.cocoapods.org/making/quality-indexes) file more. Search for “changelog” or scroll down to the section. So let’s add one :smile_cat:
It contains the same information found on the releases page on GitHub. The file structure is modelled after Alamofire’s changelog.
@8W9aG @jgavris @dflems
=> Add a change log file

SPTDataLoaderTests/SPTDataLoaderAuthoriserMock.h, SPTDataLoaderTests/SPTDataLoaderAuthoriserMock.m, SPTDataLoaderTests/SPTDataLoaderFactoryTest.m
* Tests the case of retrying after a single failure on authorisation errors from the server
=> Test Retry Authorisation

spotify_os.xcconfig
* Should only affect the open source CI
=> Treat warnings as errors

SPTDataLoaderTests/SPTDataLoaderRequestTaskHandlerTest.m
* Tests that the appending of data happens when a
non stream request has been sent
=> Add testDataAppendedWhenNotStreaming

SPTDataLoaderTests/SPTDataLoaderResolverAddressTest.m
* Tests the case when the last failed time is above
the current time
=> Add testLastFailedTimeNonsensical

SPTDataLoader/SPTDataLoaderFactory.m, SPTDataLoaderTests/SPTDataLoaderFactoryTest.m, SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerMock.h, SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerMock.m
* Tests cases when the request has an absolute
timeout explicitly defined
=> Add testRequestTimeout

SPTDataLoader/SPTDataLoaderService.m, SPTDataLoaderTests/SPTDataLoaderServiceTest.m
* Always execute the completion handler
=> Fix data loader rejecting all HTTPS traffic

README.md
* Also a little footnote over the design decision
regarding the delegate pattern over the block
pattern.
=> Add usage examples into README

SPTDataLoader/SPTDataLoader.m, SPTDataLoaderTests/SPTDataLoaderDelegateMock.h, SPTDataLoaderTests/SPTDataLoaderDelegateMock.m, SPTDataLoaderTests/SPTDataLoaderTest.m
=> Add test for different delegate queue

SPTDataLoaderTests/SPTDataLoaderRequestTaskHandlerTest.m
* Tests that NSURLErrorCancelled errors send a
cancel message to the request response handler
=> Add testCancelledError

README.md
* Add a short code example of handling streaming
requests for MP3 data
=> Add "Handling Streaming Requests" to README

README.md
* Also adds a Readme Score coming from this site: http://scoreme.report/
* Adds the usage example with code in order to make it easy for the user of the library to search for this example in the README
* This usage example is not included in the demo
=> Add Rate Limiting Specific Endpoints to README

SPTDataLoader/SPTDataLoaderService.m, SPTDataLoaderTests/SPTDataLoaderServiceTest.m
* Ensure that we don't crash
* Also remove redundant isKindOfClass check
=> Add test for nil completion block in willCacheResponse

README.md
* Provide more examples of operations not included
in current README or demo
=> Add "Switching Hosts for all requests" to README

README.md
* Not obvious how to use this API from looking at
the demo and the current README
=> Add "Using the jittered exponential timer" to README

README.md
* Another API that is not obvious from the demo
or the current README
=> Add "Consumption observation" to the README

ci/script.sh
* Due to some erroneous failures on CI, attempt
to rerun xcodebuild if the tests fail
=> Retry tests when they fail

README.md
* Although in the demo I wanted to give a little
more clarity in these docs
=> Add "Creating a custom authorizer" to the README

SPTDataLoaderTests/SPTDataLoaderServiceTest.m
* Tests redirection to different hosts from a
request containing headers
=> Add testRedirectionToDifferentHostWithHeaders

SPTDataLoader.xcodeproj/project.pbxproj, SPTDataLoader/SPTDataLoader+Private.h, SPTDataLoader/SPTDataLoaderRequest+Private.h, SPTDataLoader/SPTDataLoaderRequest.m, SPTDataLoaderTests/SPTDataLoaderRequestTest.m, SPTDataLoaderTests/SPTDataLoaderServiceTest.m
* I broke the tests with the previous separate projects PR
=> Fix Unit Tests

SPTDataLoader.xcodeproj/project.pbxproj, SPTDataLoader/SPTDataLoaderRequestTaskHandler.m, SPTDataLoaderTests/SPTDataLoaderRequestTaskHandlerTest.m, SPTDataLoaderTests/SPTDataLoaderServiceTest.m, SPTDataLoaderTests/SPTDataLoaderTest.m
* After these small tests, we will reach maximum test coverage until we make a decision of our super init code style and dealloc calling
=> Add final tests for coverage

SPTDataLoader.xcodeproj/project.pbxproj, SPTDataLoader/SPTDataLoader.m, SPTDataLoader/SPTDataLoaderCancellationTokenFactory.h, SPTDataLoader/SPTDataLoaderCancellationTokenFactoryImplementation.h, SPTDataLoader/SPTDataLoaderCancellationTokenFactoryImplementation.m, SPTDataLoader/SPTDataLoaderCancellationTokenImplementation.h, SPTDataLoader/SPTDataLoaderCancellationTokenImplementation.m, SPTDataLoader/SPTDataLoaderFactory.m, SPTDataLoader/SPTDataLoaderRequest+Private.h, SPTDataLoader/SPTDataLoaderRequest.m, SPTDataLoader/SPTDataLoaderRequestResponseHandler.h, SPTDataLoader/SPTDataLoaderService.m, SPTDataLoaderFramework.xcodeproj/project.pbxproj, SPTDataLoaderTests/SPTDataLoaderCancellationTokenDelegateMock.h, SPTDataLoaderTests/SPTDataLoaderCancellationTokenDelegateMock.m, SPTDataLoaderTests/SPTDataLoaderCancellationTokenFactoryImplementationTest.m, SPTDataLoaderTests/SPTDataLoaderCancellationTokenImplementationTest.m, SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerDelegateMock.h, SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerDelegateMock.m, SPTDataLoaderTests/SPTDataLoaderServiceTest.m, SPTDataLoaderTests/SPTDataLoaderTest.m, include/SPTDataLoader/SPTDataLoader.h, include/SPTDataLoader/SPTDataLoaderCancellationToken.h, include/SPTDataLoader/SPTDataLoaderConvenience.h
* Last file that needs changing to naming convention
=> Prefix SPTCancellationToken with SPTDataLoader

spotify_os.xcconfig
To match what we have internally.
@8W9aG @dflems @jgavris @JensAyton
=> Add langauge standards to xcconfig

README.md
* Lightweight
* Control
* Only required features
* Architecture
=> Add some more context for the creation justification

SPTDataLoader.podspec, SPTDataLoader.xcodeproj/project.pbxproj
* Will delete the previous release and re-release once merged, bit of a boo-boo on my behalf
=> Update pod spec to 1.1

SPTDataLoaderTests/SPTDataLoaderRequestTest.m
=> Use proper objc import

SPTDataLoaderDemo.xcodeproj/project.pbxproj, demo/AppDelegate.m, demo/PlaylistsViewModel.m, demo/SPTDataLoaderAuthoriserOAuth.m
This PR fixes the nullability issues in the demo project pointed out by @loretoparisi in #104, thank you!
@8W9aG @dflems @adamhowardprice @loretoparisi
=> Fix nullability issues in demo project

demo/AppDelegate.m
Little adjustment on the appDelegate from the demo.
=> getting redirect_uri from ClientKeys.h

SPTDataLoader.xcodeproj/xcshareddata/xcschemes/SPTDataLoader.xcscheme, SPTDataLoaderDemo.xcodeproj/xcshareddata/xcschemes/SPTDataLoaderDemo.xcscheme, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-OSX.xcscheme, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-TV.xcscheme, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-Watch.xcscheme, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-iOS.xcscheme
The keys changed a slight bit from 7.2 and 7.3 betas.
=> Let Xcode 7.3 touch all Xcode schemes

SPTDataLoaderTests/NSDictionaryHeaderSizeTest.m, SPTDataLoaderTests/SPTDataLoaderCancellationTokenFactoryImplementationTest.m, SPTDataLoaderTests/SPTDataLoaderCancellationTokenImplementationTest.m, SPTDataLoaderTests/SPTDataLoaderFactoryTest.m, SPTDataLoaderTests/SPTDataLoaderRateLimiterTest.m, SPTDataLoaderTests/SPTDataLoaderRequestTaskHandlerTest.m, SPTDataLoaderTests/SPTDataLoaderRequestTest.m, SPTDataLoaderTests/SPTDataLoaderResolverAddressTest.m, SPTDataLoaderTests/SPTDataLoaderResolverTest.m, SPTDataLoaderTests/SPTDataLoaderResponseTest.m, SPTDataLoaderTests/SPTDataLoaderServerTrustPolicyTest.m, SPTDataLoaderTests/SPTDataLoaderServiceTest.m, SPTDataLoaderTests/SPTDataLoaderTest.m, demo/ViewController.m
=> Remove Superfluous Code

ci/sample/codecov.yml, ci/spotify_os.xcconfig
* Needed for iOS 8.0 target deployment
=> Update ios-ci subtree

CHANGELOG.md, Info.plist, SPTDataLoader.podspec
* After this is merged will release 1.1.1
=> Bump to 1.1.1

SPTDataLoader.xcodeproj/project.pbxproj, SPTDataLoader.xcodeproj/xcshareddata/xcschemes/SPTDataLoader.xcscheme
Update project and scheme for Xcode 8.2
=> Update project and scheme for Xcode 8.2

SPTDataLoader.xcodeproj/project.pbxproj, SPTDataLoader.xcodeproj/xcshareddata/xcschemes/SPTDataLoader.xcscheme
=> Update project for Xcode 8.3

SPTDataLoader.xcodeproj/project.pbxproj, SPTDataLoader.xcodeproj/xcshareddata/xcschemes/SPTDataLoader.xcscheme
=> Update projects for Xcode 9.1

SPTDataLoader.xcodeproj/xcshareddata/xcschemes/SPTDataLoader.xcscheme, SPTDataLoaderDemo.xcodeproj/project.pbxproj, SPTDataLoaderDemo.xcodeproj/xcshareddata/xcschemes/SPTDataLoaderDemo.xcscheme, SPTDataLoaderFramework.xcodeproj/project.pbxproj, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-OSX.xcscheme, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-TV.xcscheme, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-Watch.xcscheme, SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-iOS.xcscheme
Fixes warnings about `ONLY_ACTIVE_ARCH`.
@dflems
=> Update projects for Xcode 9.2

SPTDataLoaderTests/NSURLSessionDataTaskMock.h, SPTDataLoaderTests/NSURLSessionDataTaskMock.m, SPTDataLoaderTests/NSURLSessionTaskMock.h, SPTDataLoaderTests/NSURLSessionTaskMock.m
This PR fixes the tests that were broken in #154.
@gitrema @8W9aG Can you please write some tests for the new logic?
=> Fix broken tests

SPTDataLoader/SPTDataLoaderRequest.m, SPTDataLoaderTests/SPTDataLoaderRequestTest.m, include/SPTDataLoader/SPTDataLoaderRequest.h
Adds support for the [PATCH](https://tools.ietf.org/html/rfc5789#section-2) method allowing partial updates.
For examples and motivation see the [Google Calendar API](https://developers.google.com/calendar/performance#patch) and the [GitHub REST API v3 (PR comments section)](https://developer.github.com/v3/pulls/comments/#edit-a-comment).
=> Add PATCH request method

SPTDataLoader.xcodeproj/project.pbxproj
- Updated to project not to use deprecated localization.
=> Remove usage of deprecated localization

include/SPTDataLoader/SPTDataLoaderRequest.h, include/SPTDataLoader/SPTDataLoaderResponse.h
Minor style modernization before doing other work in these headers.
=> Adopt NS_ERROR_ENUM
