.gitignore

This PR adds more files and “folders” that git should ignore. So that we don’t have to depend on users having a global ignore file.
@8W9aG

Add more ignored files and folders

---

.travis.yml
Gemfile
Gemfile.lock

Should result in output which is quite a bit easier to read. The PR also makes sure the correct locale is set.
Also opt-in to not using `sudo` this also opts us in to using the newer Travis-CI architecture.

Use xcpretty to format output when building and testing on Travis-CI

---

.gitignore
.slather.yml
ci/after_success.sh

We were calling slather twice. The second time, ignore wasn't set properly, so system framework coverage data was being posted to coveralls. This PR *should* simplify things. If this works, we can close #11.

Simplify slather + coveralls

---

README.md
SPTDataLoader.podspec

* We should make this part of our release process in the future

Podspec for 1.0.1

---

SPTDataLoader/SPTDataLoaderRequest+Private.h
include/SPTDataLoader/SPTDataLoaderRequest.h

* We need to get this so our C++ core can append the
same Accept-Language header to our proprietary
transport layer

Move languageHeaderValue to the public API

---

.cocoadocs.yml
README.md

- Add a section on how to find the generated documentation to the readme.
- Add a docs shield to the readme.
- Change the colors of the documentation generated by CocoaDocs be closer to our brand guidelines.

Tweak CocoaDocs output and add a docs badge to readme

---

README.md

- Was missing a comma, making the sentence about the Dash feed hard to read.
- Also linkifies “Dash” and “CocoaDocs.org”.
Whoopsie :stuck_out_tongue_closed_eyes:
@8W9aG @jgavris

Fix incorrect subject in readme

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoader/SPTDataLoaderExponentialTimer.m
SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
include/SPTDataLoader/SPTDataLoaderConvenience.h
include/SPTDataLoader/SPTDataLoaderExponentialTimer.h

This PR cleans the exponential timer class used for back-off. So that it complies with Spotify’s code style guidelines. It also improves the class’ API documentation as well as removing duplicate and unused methods.
The changes to the files are so large that git does not manage to detect the rename. As such the diff is _quite_ a lot larger than what it actually is.
@8W9aG @jgavris @dflems

Cleanup exponential timer

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoader/SPTDataLoaderService.m
SPTDataLoaderTests/SPTDataLoaderRateLimiterTest.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m
demo/NSString+OAuthBlob.m
demo/ViewController.h
demo/ViewController.m
include/SPTDataLoader/SPTDataLoaderService.h
project.xcconfig
spotify_os.xcconfig

* Add some more options to spotify_os.xcconfig
* Make the target inherit these settings
* Fix some more test warnings
* Add a way to allow all certificates through code rather than macros

Fix the remaining issues with no spotify_shared.xcconfig

---

.gitignore

* So when our build script changes it, it won't mark
the repo as dirty

Ignore changes in our project.xcconfig file

---

SPTDataLoader.podspec

`master` supports tvOS and watchOS so let’s declare it in our podspec.
Also fix wrong type of apostrophe in the description.
@8W9aG @jgavris @dflems

Add tvOS and watchOS to podspec

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoader/SPTDataLoaderExponentialTimer.m
SPTDataLoaderTests/SPTDataLoaderExponentialTimerTest.m

* Foot in the door for testing exponential timer
* More tests may follow

Add SPTDataLoaderExponentialTimerTest

---

SPTDataLoader/SPTDataLoaderResponse.m
SPTDataLoaderTests/SPTDataLoaderResponseTest.m

* Raise that coverage even more

Add response tests

---

SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerMock.h
SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerMock.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m

* Test cases where the request has been cancelled
during authorization

Add testPerformingCancelledRequest

---

SPTDataLoaderTests/SPTDataLoaderServiceTest.m

* Sanity checks that we don't crash when deallocating
while having requests in flight

Add testCancellingLoadsOnDealloc

---

README.md

This PR builds upon the work by @8W9aG in #54 by tweaking the copy and formatting slightly. It also adds a little bit more information on some steps. Let’s hope Coveralls doesn’t get confused by this one :stuck_out_tongue: 
Also rebases on master to be merge-able.
@8W9aG

Add installation information to readme (extends #54)

---

SPTDataLoaderTests/SPTDataLoaderServiceTest.m

* Allows us to test dealloc in a more controlled way
* I believe assuming ARC will deallocate at a specific
point is causing the CI unpredictability

Add SPTDataLoaderServiceTestNoARC

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoaderTests/NSBundleMock.h
SPTDataLoaderTests/NSBundleMock.m
SPTDataLoaderTests/SPTDataLoaderRequestTest.m
include/SPTDataLoader/SPTDataLoaderRequest.h

Add tests for Accept-Languages headers for values other than English

---

SPTDataLoader/SPTDataLoaderService.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m

* We should not cancel authentication challenges
by default when we do not allow all certificates

Delegate challenges to the default handling

---

README.md

* Shows the reader how to get block based callbacks
for the SPTDataLoader delegates

Add code example for block based callbacks

---

SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
SPTDataLoaderTests/NSURLSessionTaskMock.h
SPTDataLoaderTests/NSURLSessionTaskMock.m
SPTDataLoaderTests/SPTDataLoaderRequestTaskHandlerTest.m

* Fixes a major bug which allows infinite retries
* Extends the task mock to allow callbacks on resume
calls
* Allows configurable retry queues (other than main)

Add testRetryWithRateLimiter

---

SPTDataLoaderTests/NSURLSessionTaskMock.h
SPTDataLoaderTests/NSURLSessionTaskMock.m
SPTDataLoaderTests/SPTDataLoaderConsumptionObserverMock.h
SPTDataLoaderTests/SPTDataLoaderConsumptionObserverMock.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m

* Tests asynchronous communication with consumption
observers
* Tests size calculations on the HTTP response
headers
* Makes the mocks more comprehensive

Add testConsumptionObserverTakesIntoAccountResponseHeaders

---

SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoader/SPTDataLoaderResponse.m
SPTDataLoaderTests/SPTDataLoaderRequestTest.m
SPTDataLoaderTests/SPTDataLoaderResponseTest.m

Implement `-debugDescription` methods for `SPTDataLoaderRequest` and `SPTDataLoaderResponse`. 
Format of the output is the same as `NSURLResponse` and `NSURLRequest`.

Implement -debugDescription for Request and Response

---

SPTDataLoader/SPTDataLoader.m
SPTDataLoaderTests/SPTDataLoaderTest.m
include/SPTDataLoader/SPTDataLoaderRequest.h

* Test that an error is thrown when the data loader
attempts to load a request that requires chunks but
the delegate does not support chunks
* Removes previous assertion in favor of a less
noisy delegate error callback approach

Add testErrorDelegateCallbackWhenMismatchInChunkSupport

---

SPTDataLoaderTests/SPTDataLoaderExponentialTimerTest.m

* A couple more tests to cover the timer cases
* Removes the coverage flakiness

Add timer tests

---

include/SPTDataLoader/SPTDataLoaderRequest.h

It was causing issues with certain usage patterns where a non-NSObject subclass was saved in the userInfo dictionary. For example the [block interface hacking](https://github.com/spotify/SPTDataLoader#why-no-block-interface).
:crying_cat_face: 
@JohnSundell

Remove NSObject type info for userInfo

---

.slather.yml
.travis.yml
ci/after_success.sh
ci/lib/travis_helpers.sh
ci/script.sh

- Extract project and scheme values for Slather from the scripts to the config file.
- Extract podspec name from the scripts to the config file.
- Make it easier to run CI script locally by setting the TRAVIS environment variable to a default (only if not yet set).
@jgavris @dflems

Tweak the CI scripts a bit

---

SPTDataLoader.podspec

We’ve removed the file on disk.
@dflems @adamhowardprice @8W9aG

Remove reference to modulemap in podspec

---

SPTDataLoader/SPTDataLoader.m
SPTDataLoader/SPTDataLoaderCancellationTokenImplementation.m
SPTDataLoader/SPTDataLoaderFactory.m
SPTDataLoader/SPTDataLoaderRateLimiter.m
SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoader/SPTDataLoaderRequestTaskHandler.h
SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
SPTDataLoader/SPTDataLoaderResolverAddress.m
SPTDataLoader/SPTDataLoaderResponse.m
SPTDataLoader/SPTDataLoaderService.m
include/SPTDataLoader/SPTDataLoader.h

Caught by running the analyzer bundled with Xcode 7.3 beta 3. Most of the problems were due to the early-return segment of the init methods:
Also fixed a the type of some methods that should return `nil` as well as updated the documentation for those.

Fix nil-returns from methods with nonnull return type

---

SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoader/SPTDataLoaderResponse.m
SPTDataLoaderTests/SPTDataLoaderRequestTest.m
SPTDataLoaderTests/SPTDataLoaderResponseTest.m

This PR moves the `-debugDescription` implementation to the `-description` method instead. The reasoning being that it makes debugging easier if a request or response object is logged instead of printed using the debugger.
Also aligns the format with Apple’s standard (`<ClassName: 0xDEADBEEF property-1 = "string value"; property-2 = 42>`).

Move -debugDescription implementation to -description method for improved debugability

---

SPTDataLoader.podspec

Fixes some issues, adds some more stuff and standardizes the podspec.
- Adds a link to our [Spotify Engineering Twitter](http://twitter.com/spotifyeng) account.
- Fixes iOS deployment target. It was set to 6.0 even though we only support 7.0 and up.
- Fixes use of incorrect apostrophe character.
- Re-formats the podspec making sure we use only one type of quote character. As well as some other small changes to the formatting.

Podspec fixes

---

Gemfile
Gemfile.lock

As we don’t use it anymore. Also bumps other gems.

Remove Slather

---

SPTDataLoader.xcodeproj/project.pbxproj

Only happens with certain build system configurations. This PR resolves it by always using a very specific `HEADER_SEARCH_PATHS` that **MUST NOT** include `$(inherited)`.
@8W9aG @dflems @spotify/objc-dev

Fix a potential issue where we could end up with duplicate symbols

---

SPTDataLoader/SPTDataLoaderRateLimiter.m

Should fix this:
SPTDataLoaderRateLimiter.m 
`131`: Implicitly checking whether `NSNumber` pointer value is nil at line `131`, column `16`. Did you mean to compare against the unboxed value instead? Please either explicitly compare value to nil or use one of the `NSNumber` accessors before the comparison.

Fix BAD_POINTER_COMPARISON (infer warning)

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoader/SPTDataLoader+Private.h
SPTDataLoader/SPTDataLoader.m
SPTDataLoader/SPTDataLoaderFactory.m
SPTDataLoader/SPTDataLoaderRequestResponseHandler.h
SPTDataLoader/SPTDataLoaderService.m
SPTDataLoaderTests/SPTDataLoaderCancellationTokenFactoryMock.h
SPTDataLoaderTests/SPTDataLoaderCancellationTokenFactoryMock.m
SPTDataLoaderTests/SPTDataLoaderFactoryTest.m
SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerDelegateMock.h
SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerDelegateMock.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m
SPTDataLoaderTests/SPTDataLoaderTest.m

* Currently when the user cancels the cancellation token we receive this delegate callback in the SPTDataLoaderService
* The SPTDataLoaderService then proceeds to cancel the associated data task
* This would then asynchronously cancel the request, once cancelled that message was forwarded up to the SPTDataLoader which would then alert the delegate
* The problem occurs because of the asynchronousity of the data task cancellation, we could theoretically receive an error or success message before we cancel the data task despite the fact that the cancellation came first
* We will solve this problem by cancelling requests in SPTDataLoader instead and disallowing them  to bubbled up to the UI immediately once cancelled, and perform the actual cancel further down the stack

Fix cancellation race condition

---

SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoaderTests/SPTDataLoaderRequestTest.m

* Prevents requests from increasing by 2 on each
perform request rather than just by 1

Do not increase the unique identifier barrier on copy

---

SPTDataLoader/SPTDataLoaderRequestTaskHandler.h
SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
SPTDataLoader/SPTDataLoaderService.m
include/SPTDataLoader/SPTDataLoaderService.h

Adding nullability annotations to reflect what it says in the README under `Creating the SPTDataLoaderService` so clients don't get a warning for passing in nil.
> Note that you can provide all these as nils if you are so inclined, it may be for the best to use nils until you identify a need for these different configuration options.

Nullability annotations for user agent, rate limiter and resolver

---

SPTDataLoaderFramework.xcodeproj/project.pbxproj

Using rpath in the install_name instructs the linker to search for a list of locations for the library.
Currently, if you try to use SPTDataLoader in another framework Foo.framework, clients of Foo.framework will run into `dyld: Library not loaded` on startup and crash.
https://www.mikeash.com/pyblog/friday-qa-2009-11-06-linking-and-install-names.html

Use rpath in install_name

---

SPTDataLoader/SPTDataLoaderRequestTaskHandler.h
SPTDataLoader/SPTDataLoaderService.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m

* Issue 1: The task property was nonatomic while being accessed from different threads, this is a no no
* Issue 2: There are race conditions which can lead to handlers not being associated with a task, this is solved

Fix Race Conditions associated with new tasks for retries

---

SPTDataLoader/SPTDataLoader.m
SPTDataLoader/SPTDataLoaderFactory.m
SPTDataLoader/SPTDataLoaderRequestResponseHandler.h
SPTDataLoader/SPTDataLoaderRequestTaskHandler.h
SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
SPTDataLoader/SPTDataLoaderService.m
SPTDataLoaderTests/SPTDataLoaderDelegateMock.h
SPTDataLoaderTests/SPTDataLoaderDelegateMock.m
SPTDataLoaderTests/SPTDataLoaderFactoryTest.m
SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerMock.h
SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerMock.m
SPTDataLoaderTests/SPTDataLoaderRequestTaskHandlerTest.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m
SPTDataLoaderTests/SPTDataLoaderTest.m
include/SPTDataLoader/SPTDataLoaderDelegate.h

This is needed in certain cases when the new `bodyStream`-property is used on the `SPTDataLoaderRequest`.

Exposes a new method to handle cases where the NSURLSessionTask needs a new body stream due to redirects.

---

SPTDataLoader/SPTDataLoaderExponentialTimer.m

Also such change avoids devision by zero that can happen in rare cases

Use half open interval [0, 1) as original algorithm does

---

SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoaderTests/SPTDataLoaderRequestTest.m
include/SPTDataLoader/SPTDataLoaderRequest.h

* Adds ability for data loader to support HEAD requests
* Really useful for checking whether an item is available on a CDN without downloading the whole thing

Add HEAD request method support

---

SPTDataLoaderTests/SPTDataLoaderFactoryTest.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m

Calling `[NSError new]` triggers this log message:
> -[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:.
@cerihughes

Fix misuse of NSError in unit tests

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoader/SPTDataLoaderRequest.m
SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
SPTDataLoader/SPTDataLoaderService.m
SPTDataLoaderFramework.xcodeproj/xcshareddata/xcschemes/SPTDataLoader-OSX.xcscheme
SPTDataLoaderTests/NSDataMock.h
SPTDataLoaderTests/NSDataMock.m
SPTDataLoaderTests/NSFileManagerMock.h
SPTDataLoaderTests/NSFileManagerMock.m
SPTDataLoaderTests/NSURLSessionDownloadTaskMock.h
SPTDataLoaderTests/NSURLSessionDownloadTaskMock.m
SPTDataLoaderTests/NSURLSessionMock.m
SPTDataLoaderTests/SPTDataLoaderRequestTaskHandlerTest.m
SPTDataLoaderTests/SPTDataLoaderRequestTest.m
SPTDataLoaderTests/SPTDataLoaderServiceTest.m
include/SPTDataLoader/SPTDataLoaderRequest.h
include/SPTDataLoader/SPTDataLoaderService.h

Rather than always using a data task to make requests, this change allows a "background policy" to be set on requests that determine when/if a background task is created:
- **Default**: Allow the system to fail in-flight requests in the background
- **OnDemand**: Upgrade data tasks to background tasks after receiving response headers
- **Always**: Use a background task at the start, don't return response headers/status code
Background tasks are important for long-running requests which may be killed by the operating system when the application loses foreground focus. It's possible to improve the reliability of such requests by using a download task instead.
This change is backwards compatible. The default policy (.Default) is to always use a data task as before.

Add background download task support

---

SPTDataLoader.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
SPTDataLoader/SPTDataLoaderRequestResponseHandler.h
SPTDataLoaderTests/SPTDataLoaderRequestResponseHandlerDelegateMock.h

* Add `IDEWorkspaceChecks.plist` (automatically added by Xcode 9.3+)
* Remove an unused forward declaration

Project tweaks

---

SPTDataLoader/SPTDataLoader.m
SPTDataLoaderTests/SPTDataLoaderTest.m

Prevents loitering of token/request objects as mentioned in https://github.com/spotify/SPTDataLoader/issues/147.

Remove cancellation token along with request

---

SPTDataLoader/SPTDataLoader.m

While refactored code is correct, mutation of collection while iterating it always raises a warning.
Proposed change is more CPU effective as removal of multiple array elements in one call avoids
multiple buffer copying and possible array storage deallocation.
Price for that effectives - need for storage of indices in NSMutableIndexSet.

Refactors removing cancellation tokens avoiding mutation of array during iterating it

---

SPTDataLoader/SPTDataLoader.m

Everywhere else we `@synchronize` on `self.requests`

Synchronize on currentRequests

---

include/SPTDataLoader/SPTDataLoaderResponse.h

In #174 I changed this from `NS_ENUM` to `NS_ERROR_ENUM` for modern style and better bridging to Swift. However, it turns out that `SPTDataLoaderResponseHTTPStatusCode` is used _both_ as an `NSError` code and in other contexts, which is terribad and breaks things.
See https://github.com/spotify/SPTDataLoader/commit/5f62f06b955dac2cd5ccb4dea27be73dad5d39af#r35424354
@dmakarov @gitrema

Turn SPTDataLoaderResponseHTTPStatusCode back to a regular enum

---

ci/run.sh

This should fix building on CI, since it seems that the image has been updated by GitHub and builds started failing with:
```
xcodebuild: error: Failed to build workspace SPTDataLoader with scheme SPTDataLoader-iOS.
Reason: The run destination My Mac is not valid for Running the scheme 'SPTDataLoader-iOS'.
Recovery suggestion: My Mac doesn’t support any of SPTDataLoader.framework’s architectures. You can add My Mac’s x86_64 architecture to SPTDataLoader.framework’s Architectures build setting.
```

Specify SDK parameter when building framework

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoaderFramework.xcodeproj/project.pbxproj
Sources/SPTDataLoader.m
Sources/SPTDataLoaderFactory.m
Sources/SPTDataLoaderRequest.m
Sources/SPTDataLoaderRequestResponseHandler.h
Sources/SPTDataLoaderRequestTaskHandler.h
Sources/SPTDataLoaderRequestTaskHandler.m
Sources/SPTDataLoaderService+Private.h
Sources/SPTDataLoaderService.m
Sources/SPTDataLoaderServiceSessionSelector.h
Sources/SPTDataLoaderServiceSessionSelector.m
Tests/SPTDataLoaderRequestResponseHandlerMock.m
Tests/SPTDataLoaderServiceSessionSelectorMock.h
Tests/SPTDataLoaderServiceSessionSelectorMock.m
Tests/SPTDataLoaderServiceTest.m
include/SPTDataLoader/SPTDataLoaderDelegate.h
include/SPTDataLoader/SPTDataLoaderRequest.h

* Adds `waitForConnectivity` flag to `SPTDataLoaderRequest`
* Adds a mechanism to support multiple `NSURLSession`s and select between them for each request
* Routes `waitingForConnectivity` notification through the various layers
Missing:
- ~[ ] Tests~ — not effectively testable

Add per-request waitsForConnectivity flag

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

I couldn't find a way to see which version we're currently using, but each macOS image has multiple Xcode versions installed. Since we're also targeting `macOS-latest`, if the image changes, also the Xcode version might change and our builds could suddenly break (like in #183).

Pin Xcode version to 11.1

---

Sources/SPTDataLoaderResponse.m
Tests/SPTDataLoaderResponseTest.m
include/SPTDataLoader/SPTDataLoaderResponse.h

After following redirects, the value in `-[NSURLResponse URL]` may be different from that of the request. There are instances where we want to capture this.

Add resolvedURL property to response object

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoaderFramework.xcodeproj/project.pbxproj
Sources/SPTDataLoaderRateLimiter+Private.h
Sources/SPTDataLoaderRateLimiter.m
Sources/SPTDataLoaderTimeProvider.h
Sources/SPTDataLoaderTimeProviderImplementation.h
Sources/SPTDataLoaderTimeProviderImplementation.m
Tests/SPTDataLoaderRateLimiterTest.m
Tests/SPTDataLoaderTimeProviderImplementationTest.m
Tests/SPTDataLoaderTimeProviderMock.h
Tests/SPTDataLoaderTimeProviderMock.m

**Context**
The `SPTDataLoaderRateLimiter` has a method to compute when is earliest time a new request can be executed: `earliestTimeUntilRequestCanBeExecuted`. This includes a throttle to avoid that too many requests are sent in a very short period of time. The object is initialised with a `requestsPerSecond` parameter which then determines the minimum waiting time between two requests: `1 / requestsPerSecond`.
The lines that apply this logic as follows:
```
CFAbsoluteTime deltaTime = currentTime - lastExecution;
CFAbsoluteTime cutoffTime = 1.0 / requestsPerSecond;
CFAbsoluteTime timeInterval = cutoffTime - deltaTime;
if (timeInterval < 0.0) {
timeInterval = 0.0;
}
return timeInterval;
```
**Problem**
In normal conditions `currentTime` is always going to be larger than `lastExecution`. …

Fix issue that was making the DataLoaderRateLimiter delaying requests unnecessarily if the system clock was moved backwards

---

CHANGELOG.md
README.md
SPTDataLoader.podspec
Sources/SPTDataLoaderFactory.m
Tests/SPTDataLoaderAuthoriserMock.m
demo/SPTDataLoaderAuthoriserOAuth.m
include/SPTDataLoader/SPTDataLoaderAuthoriser.h

Sometimes authorizers need to make decisions based on the response they are getting.
This pr changes the public interface of the authorizer to receive `SPTDataLoaderResponse` in addition to `SPTDataLoaderRequest`.
this is a breaking change

SPTDataLoaderAuthorizer requestFailedAuthorisation accept response now

---

SPTDataLoader.xcodeproj/project.pbxproj
SPTDataLoaderFramework.xcodeproj/project.pbxproj
Sources/SPTDataLoaderBlockWrapper.m
Sources/SPTDataLoaderFactory.m
Tests/SPTDataLoaderBlockWrapperTest.m
Tests/SPTDataLoaderFactoryTest.m
include/SPTDataLoader/SPTDataLoader.h
include/SPTDataLoader/SPTDataLoaderBlockWrapper.h
include/SPTDataLoader/SPTDataLoaderFactory.h

Looking at usages of Data Loader within Spotify and specifically in Swift features, many engineers are looking for a block based API to handle the common cases of data loading. 
This idea was already explored in https://github.com/spotify/SPTDataLoader/pull/186 but seemed to have been abandoned. 
This PR builds on top of the previous discussion and creates a thin wrapper that provides a block based API. The API design should also nudge users to handle the error case.
@dflems @erikprice @themackworth @JensAyton @rastersize

Data loader: add a thin wrapper with a simple block API

---

Sources/SPTDataLoaderBlockWrapper.m
Tests/SPTDataLoaderBlockWrapperTest.m

- pass nil error in case of successful response and error in case of failure, update unit tests
- fix block based api to pass an error back in case of failure

STPDataLoaderBlockWrapper: Fix callbacks

---

Sources/SPTDataLoaderRequest.m
Tests/SPTDataLoaderRequestTest.m

Anecdotally, it seems that NSBundle.preferredLocalizations can return
a list containing duplicate values.

Accept-Language: deduplicate preferred localizations

---

ci/run.sh
codecov.yml

Fix codecov ignores to ignore tests.
Build for testing into different derived data paths per-platform. Right now, the "last in wins" so we only get information for the last test target that ran in CI. This changes it to invoke codecov once per-platform and adds the `-F` flag to tag them as such.
This PR will probably fail the coverage check because of the large delta, but subsequent PRs should be a little happier.

Fix coverage, segment per-platform

---

Sources/SPTDataLoaderSwift/DataLoaderWrapper.swift
Sources/SPTDataLoaderSwift/Request.swift
Tests/SPTDataLoaderSwift/RequestTest.swift

This is a small optimization to prevent rare cases where objects linger in memory when the API user creates a request without executing it. Request removal should now always occur because they will only be added if a `perform` is attempted — which ultimately leads to a response handler removing the stored request.

Swift: Defer request storage until execution

---

Sources/SPTDataLoaderSwift/DataLoader.swift
Sources/SPTDataLoaderSwift/DataLoaderWrapper.swift
Tests/SPTDataLoaderSwift/DataLoaderWrapperTest.swift

Provides convenience methods for obtaining and cancelling active requests, similar to those of the underlying `SPTDataLoader`.
cc @zvonicek

Swift: Add active request convenience methods

---

Sources/SPTDataLoader/SPTDataLoaderServerTrustPolicy.m

SecTrustEvaluate API had been deprecated since iOS 12 and removed in
iOS13.

use SecTrustEvaluateWithError for iOS12+ target

---

ci/run.sh

Use generic destinations instead of `-sdk` to remove a bunch of noisy stuff xcodebuild writes to stderr. Also switches from the outdated `xcpretty` to [`xcbeautify`](https://github.com/thii/xcbeautify).

Reduce CI noise

---

Sources/SPTDataLoaderSwift/DataLoaderError.swift
Sources/SPTDataLoaderSwift/Request.swift
Sources/SPTDataLoaderSwift/ResponseSerializer.swift
Tests/SPTDataLoaderSwift/DataResponseSerializerTest.swift
Tests/SPTDataLoaderSwift/DecodableResponseSerializerTest.swift
Tests/SPTDataLoaderSwift/JSONResponseSerializerTest.swift
Tests/SPTDataLoaderSwift/RequestTest.swift

Adds status code response validators to make it easier to enforce the same `response.result` behavior as pre-#212.
Removes serializer `response.error` forwarding because serializers do not run if an error has already occurred, so this code was not really doing anything.

Swift: Add status code response validator

---

Sources/SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
Tests/SPTDataLoader/SPTDataLoaderRequestTaskHandlerTest.m

This PR fixes a bug in retry mechanism of Objective-C-based SPTDataLoader. The bug appears when the retry count is greater than zero, one or more initial requests fail with non-empty payload (such human-readable error message) and n-th request finally succeeds with non-empty payload. In this case the payload contains all the previous payloads prepended to the succeeding payload.
This can be fixed by strictly _nil_-ing the `receivedData` property before a request (no matter if initial or retried) starts.

Fix invalid response body on retried request

---

Tests/SPTDataLoader/Utilities/NSDataMock.m

Fixes Xcode 13.3 build error: `Parameter 'errorPtr' set but not used`
SeeAlso: [Creating and Returning NSError Objects](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/CreateCustomizeNSError/CreateCustomizeNSError.html#//apple_ref/doc/uid/TP40001806-CH204-SW5)

Correct errorPtr usage in NSDataMock

---

Sources/SPTDataLoader/SPTDataLoaderRequestTaskHandler.m

This is basically a revert for
https://github.com/spotify/SPTDataLoader/commit/844112c2a56adcf5889af91b49ebd1ad21befe17
It is actually not clear how enumerateByteRangesUsingBlock can fix any
crash there but on the other hand is causing unnecessary callback and
delay in data delivering.

Don't use enumerateByteRangesUsingBlock

---

ci/spotify_os.xcconfig

The distributable frameworks for the latest release could not be built on an M1 due to unavailable architectures. I've tried to capture all of the current device architectures here, but it's possible I've overlooked some combinations.

Update build architectures

---

Sources/SPTDataLoader/SPTDataLoaderService.m
Tests/SPTDataLoader/SPTDataLoaderServiceTest.m

Certain URL types [supported](https://developer.apple.com/documentation/foundation/nsurlsession?language=objc#2934752) by `NSURLSession` are valid even though they do not contain a `host` property. Previously, the data loader would not even attempt to request these URLs. With this change it is possible to load local files as well as data URIs.

Allow performing requests for URLs that do not contain a host

---

Sources/SPTDataLoaderSwift/Request+Combine.swift
Sources/SPTDataLoaderSwift/Request+Concurrency.swift
Sources/SPTDataLoaderSwift/Request.swift
Tests/SPTDataLoaderSwift/RequestTest.swift

Follows the common convention of including a type parameter, allowing the API call site to read a little nicer in cases where the response type cannot be inferred (or needs to differ from what's inferred).
Example:
```swift
struct SomeDecodable: Decodable {
let value: Bool
}
// Before
responseDecodable { (response: Response<SomeDecodable, Error>) in
methodAcceptingOptionalBool(response.result.success?.value)
}
// After
responseDecodable(type: SomeDecodable.self) { response in
methodAcceptingOptionalBool(response.result.success?.value)
}
```

Swift: Add decodable response type parameter

---

Sources/SPTDataLoader/SPTDataLoaderRequest.m
Sources/SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
Tests/SPTDataLoader/SPTDataLoaderRequestTaskHandlerTest.m
Tests/SPTDataLoader/SPTDataLoaderRequestTest.m
include/SPTDataLoader/SPTDataLoaderRequest.h

- Add a bool `shouldStopRedirection` to `SPTDataLoaderRequest`
- Currently url redirection happens automatically when using SPTDataLoader. To give user more control over the http url redirection a bool `shouldStopRedirection` is added to `SPTDataLoaderRequest`.

Add shouldStopRedirection to SPTDataLoaderRequest

---

Sources/SPTDataLoader/SPTDataLoaderService.m
Tests/SPTDataLoader/SPTDataLoaderServiceTest.m

On a session invalidation, tasks are usually requested to be cancelled. the `didCompleteWithError` attempts always to create a new task even if the task had been cancelled. That is usally not an issue unless the session has been invalidated. In that case a NSGenericException is raied and the app most likely crashes.

Add a safeguard on NSURLSession invalidation

---

SPTDataLoader.xcodeproj/project.pbxproj
Sources/SPTDataLoader/SPTDataLoaderRequestTaskHandler.h
Sources/SPTDataLoader/SPTDataLoaderRequestTaskHandler.m
Sources/SPTDataLoader/SPTDataLoaderService.m
Tests/SPTDataLoader/SPTDataLoaderRequestTaskHandlerTest.m
Tests/SPTDataLoader/Utilities/SPTDataLoaderRequestTaskHandlerDelegateMock.h
Tests/SPTDataLoader/Utilities/SPTDataLoaderRequestTaskHandlerDelegateMock.m

This is an approach for the small improvement I mentioned for https://github.com/spotify/SPTDataLoader/pull/229. The task is currently being reset in all completion scenarios except for cancellation, so this change narrows that behavior to only occur before starting a retry.

Add task handler delegate

---

Sources/SPTDataLoader/SPTDataLoaderService.m
Tests/SPTDataLoader/SPTDataLoaderServiceTest.m
Tests/SPTDataLoader/Utilities/SPTDataLoaderServiceSessionSelectorMock.m

Authoriser are not cancellable and so after calling `invalidateAndCancel` method on the SPTDataLoaderService some in-flight request still going through authoriser might end up to create a URLSessionTask on an already invalidated one with the result of a throwing exception

Prevent a task to be created from an invalid session

---

Sources/SPTDataLoader/SPTDataLoaderService.m

To avoid potential double reporting of a cancelled request move the check for session invalidation just before the task creation

Check for cancellation first

---

Sources/SPTDataLoader/SPTDataLoaderResponse.m
Tests/SPTDataLoader/SPTDataLoaderRequestTaskHandlerTest.m
Tests/SPTDataLoader/SPTDataLoaderResponseTest.m

Updated the retry logic in `SPTDataLoader` to exclude 404 Not Found from retryable HTTP status codes. Previously, 404 responses were retried by default, which could lead to unnecessary network requests and delays.

Fix: Do Not Retry on 404 HTTP Status Code
